bootstrap.servers=localhost:9092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
group.id=va-consumer-group
auto.offset.reset=earliest
enable.auto.commit=true
run.duration.seconds=60